
## Cluster Fill Rates for 1200 CSAFE Handwriting Database Samples {.unnumbered}


### Description

A dataset containing cluster fill rates for for 1,200 handwriting samples from
the CSAFE Handwriting Database. The dataset was created by running
'get_cluster_fill_rates' on the cluster fill counts data frame 'cfc'. Cluster
fill rates are calculated by calculating the proportion of total graphs assigned
to each cluster.



### Usage

<pre><code class='language-R'>cfr
</code></pre>


### Format

A data frame with 1200 rows and 42 variables:


<dl>
<dt>docname</dt><dd>file name of the handwriting sample
</dd>
<dt>total_graphs</dt><dd>the total number of graphs in the handwriting sample
</dd>
<dt>cluster1</dt><dd>number of graphs in cluster 1
</dd>
<dt>cluster2</dt><dd>number of graphs in cluster 2
</dd>
<dt>cluster3</dt><dd>number of graphs in cluster 3
</dd>
<dt>cluster4</dt><dd>number of graphs in cluster 4
</dd>
<dt>cluster5</dt><dd>number of graphs in cluster 5
</dd>
<dt>cluster6</dt><dd>number of graphs in cluster 6
</dd>
<dt>cluster7</dt><dd>number of graphs in cluster 7
</dd>
<dt>cluster8</dt><dd>number of graphs in cluster 8
</dd>
<dt>cluster9</dt><dd>number of graphs in cluster 9
</dd>
<dt>cluster10</dt><dd>number of graphs in cluster 10
</dd>
<dt>cluster11</dt><dd>number of graphs in cluster 11
</dd>
<dt>cluster12</dt><dd>number of graphs in cluster 12
</dd>
<dt>cluster13</dt><dd>number of graphs in cluster 13
</dd>
<dt>cluster14</dt><dd>number of graphs in cluster 14
</dd>
<dt>cluster15</dt><dd>number of graphs in cluster 15
</dd>
<dt>cluster16</dt><dd>number of graphs in cluster 16
</dd>
<dt>cluster17</dt><dd>number of graphs in cluster 17
</dd>
<dt>cluster18</dt><dd>number of graphs in cluster 18
</dd>
<dt>cluster19</dt><dd>number of graphs in cluster 19
</dd>
<dt>cluster20</dt><dd>number of graphs in cluster 20
</dd>
<dt>cluster21</dt><dd>number of graphs in cluster 21
</dd>
<dt>cluster22</dt><dd>number of graphs in cluster 22
</dd>
<dt>cluster23</dt><dd>number of graphs in cluster 23
</dd>
<dt>cluster24</dt><dd>number of graphs in cluster 24
</dd>
<dt>cluster25</dt><dd>number of graphs in cluster 25
</dd>
<dt>cluster26</dt><dd>number of graphs in cluster 26
</dd>
<dt>cluster27</dt><dd>number of graphs in cluster 27
</dd>
<dt>cluster28</dt><dd>number of graphs in cluster 28
</dd>
<dt>cluster29</dt><dd>number of graphs in cluster 29
</dd>
<dt>cluster30</dt><dd>number of graphs in cluster 30
</dd>
<dt>cluster31</dt><dd>number of graphs in cluster 31
</dd>
<dt>cluster32</dt><dd>number of graphs in cluster 32
</dd>
<dt>cluster33</dt><dd>number of graphs in cluster 33
</dd>
<dt>cluster34</dt><dd>number of graphs in cluster 34
</dd>
<dt>cluster35</dt><dd>number of graphs in cluster 35
</dd>
<dt>cluster36</dt><dd>number of graphs in cluster 36
</dd>
<dt>cluster37</dt><dd>number of graphs in cluster 37
</dd>
<dt>cluster38</dt><dd>number of graphs in cluster 38
</dd>
<dt>cluster39</dt><dd>number of graphs in cluster 39
</dd>
<dt>cluster40</dt><dd>number of graphs in cluster 40
</dd>
</dl>



### Source

&lt;https://forensicstats.org/handwritingdatabase/&gt;


