## Expand CSAFE Handwriting Database Document Names {.unnumbered}


### Description

Documents from the CSAFE Handwriting Database contain the writer, session,
prompt, and repetition in the file name:
&lt;writer&gt;_&lt;session&gt;_&lt;prompt&gt;_&lt;repetition&gt;. Create writer, session, prompt, and
repetition columns by extracting these items from the document file names.
The original document name column will be kept.



### Usage

<pre><code class='language-R'>expand_docnames(df, docname_col = "docname", suffix = "")
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="df">df</code></td>
<td>
A data frame of containing at least one column of document names
from the CSAFE Handwriting Database.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="docname_col">docname_col</code></td>
<td>
The name of the column containing document names.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="suffix">suffix</code></td>
<td>
A character string to add to the end of the new columns. Use &quot;&quot;
for no suffix.
</td></tr>
</table>


### Value

A data frame with new columns: writer, session, prompt, and repetition.



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE}
library(handwriterRF)

df <- expand_docnames(cfr, "docname", "")
df <- expand_docnames(cfr, "docname", "_1")



```
