## Get Distances {.unnumbered}


### Description

Calculate distances using between all pairs of cluster fill rates in a data
frame using one or more distance measures. The available distance measures
absolute distance, Manhattan distance, Euclidean distance, maximum distance,
and cosine distance.



### Usage

<pre><code class='language-R'>get_distances(df, distance_measures)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="df">df</code></td>
<td>
A data frame of cluster fill rates created with
<code>get_cluster_fill_rates</code>
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="distance_measures">distance_measures</code></td>
<td>
A vector of distance measures. Use 'abs' to
calculate the absolute difference, 'man' for the Manhattan distance, 'euc'
for the Euclidean distance, 'max' for the maximum absolute distance, and
'cos' for the cosine distance. The vector can be a single distance, or any
combination of these five distance measures.
</td></tr>
</table>


### Details

The absolute distance between two n-length vectors of cluster fill rates, a
and b, is a vector of the same length as a and b. It can be calculated as
abs(a-b) where subtraction is performed element-wise, then the absolute
value of each element is returned. More specifically, element i of the vector is <code class="reqn">|a_i
- b_i|</code> for $i=1,2,...,n$.

The Manhattan distance between two  n-length vectors of cluster fill rates, a and b, is
$\sum_{i=1}^n |a_i - b_i|$. In other words, it is the sum of the absolute
distance vector.

The Euclidean distance between two  n-length vectors of cluster fill rates, a and b, is
$\sqrt{\sum_{i=1}^n (a_i - b_i)^2}$. In other words, it is the sum of the elements of the
absolute distance vector.

The maximum distance between two n-length vectors of cluster fill rates, a and b, is
$\max_{1 \leq i \leq n}{\{|a_i - b_i|\}}$. In other words, it is the sum of the elements of the
absolute distance vector.

The cosine distance between two n-length vectors of cluster fill rates, a and b, is
$\sum_{i=1}^n (a_i - b_i)^2 / (\sqrt{\sum_{i=1}^n a_i^2}\sqrt{\sum_{i=1}^n b_i^2})$.



### Value

A data frame of distances



### Examples
```{r, warning=FALSE, message=FALSE, eval=FALSE}
library(handwriterRF)

# calculate maximum and Euclidean distances between the first 3 documents in cfr.
distances <- get_distances(df = cfr[1:3, ], distance_measures = c("max", "euc"))

# calculate absolute and Euclidean distances between all documents in cfr.
distances <- get_distances(df = cfr, distance_measures = c("abs", "euc"))
```
