## A <span class="pkg">ranger</span> Random Forest, Distances, and Densities {.unnumbered}


### Description

A list that contains a trained random forest created with <span class="pkg">ranger</span>, the data
frame of distances used to train the random forest, and two densities
obtained from the random forest.



### Usage

<pre><code class='language-R'>random_forest
</code></pre>


### Format

A list with the following components:


<dl>
<dt>dists</dt><dd>The data frame used to train the random forest. The data frame has
600 rows. Each row contains the absolute and Euclidean distances between the
cluster fill rates of two handwriting samples. If both handwriting samples are
from the same writer, the class is 'same'. If the handwriting samples are from
different writers, the class is 'different'. There are 300 'same' distances and
300 'different' distances in the data frame.
</dd>
<dt>rf</dt><dd>A random forest created with <span class="pkg">ranger</span> with settings:
importance = 'permutation', scale.permutation.importance = TRUE, and num.trees = 200.
</dd>
<dt>densities</dt><dd>A similarity score was obtained for each pair of handwriting samples in the
training data frame, dists, by calculating the proportion of decision trees that voted 'same'
class for the pair. The 'same_writer' density was created by applying <code>density</code>
to the similarity scores for the 300 same writer pairs in dists. Similarly, the 'diff_writer'
density was created by applying the <code>density</code> function to the similarity scores for the 300
different writer pairs in dists. The default settings were used with <code>density</code>.
</dd>
</dl>



### Examples
```{r, warning=FALSE, message=FALSE, eval=FALSE}
library(handwriterRF)

# view the random forest
random_forest$rf

# view the distances data frame
random_forest$dists

# plot the same writer density
plot(random_forest$densities$same_writer)

# plot the different writer density
plot(random_forest$densities$diff_writer)
```
