## Train a Random Forest {.unnumbered}


### Description

Train a random forest with <span class="pkg">ranger</span> from a data frame of cluster fill rates.



### Usage

<pre><code class='language-R'>train_rf(
  df,
  ntrees,
  distance_measures,
  output_dir = NULL,
  run_number = 1,
  downsample = TRUE
)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="df">df</code></td>
<td>
A data frame of cluster fill rates created with
<code>get_cluster_fill_rates</code>
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="ntrees">ntrees</code></td>
<td>
An integer number of decision trees to use
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="distance_measures">distance_measures</code></td>
<td>
A vector of distance measures. Any combination of
'abs', 'euc', 'man', 'max', and 'cos' may be used.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="output_dir">output_dir</code></td>
<td>
A path to a directory where the random forest will be
saved.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="run_number">run_number</code></td>
<td>
An integer used for both the set.seed function and to
distinguish between different runs on the same input data frame.
</td></tr>
<tr><td style = "white-space: nowrap; font-family: monospace; vertical-align: top"><code id="downsample">downsample</code></td>
<td>
Whether to downsample the number of 'different writer'
distances before training the random forest. If TRUE, the different writer
distances will be randomly sampled, resulting in the same number of
different writer and same writer pairs.
</td></tr>
</table>


### Value

A random forest



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE}
library(handwriterRF)

train <- get_csafe_train_set(df = cfr, train_prompt_code = 'pCMB')
rforest <- train_rf(
  df = train,
  ntrees = 200,
  distance_measures = c('euc'),
  run_number = 1,
  downsample = TRUE
)


```
