---
title: "Random Forest with Wizard of Oz"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(gtools)
library(randomForest)
source("handwriting_reformat.R")
source("calc_dist.R")
source("kde_slr_functions.R")
d1<-readRDS("d1.Rdata")

#filter just the wizard of oz prompts
w<-d1 %>% filter(prompt=="WOZ") 
```

#Method 3

```{r}
#sample of 80% of the writers
#same as in Method 3 with the London Letters but now looking at Wizard of Oz prompt

n_writers<-n_distinct(w$writer)

#randomly select 80% of the total writers
samp_writers2 <- w %>% dplyr::select(writer) %>% unique() %>%
  sample_n(ceiling(.8*n_writers))

#dataset with the documents from only the sampled writers
w_writers2 <- w %>% filter(writer %in% samp_writers2$writer)

#all document combinations of size of the sampled dataset
pairs_writers2 <- combinations(nrow(w_writers2),2)
pairs_writers2_df <- as.data.frame(combinations(nrow(w_writers2),2)) %>%
  rename(row1=V1,row2=V2) %>% mutate(row1=as.numeric(row1), row2=as.numeric(row2))

#count number of combinations from same and different writers
row_writer<-as.data.frame(cbind(c(1:dim(w_writers2)[1]),w_writers2$writer)) %>%
  rename(row=V1,writer=V2) %>% mutate(row=as.numeric(levels(row))[row])

writers_combo<-left_join(pairs_writers2_df,row_writer, by=c("row1"="row")) %>% 
  left_join(row_writer, by=c("row2"="row"))
same_number<-writers_combo %>% filter(writer.x==writer.y) %>% summarise(n())

#random sample of the same number of different sources
diff_sources<-writers_combo %>% filter(!writer.x==writer.y) %>% sample_n(same_number[[1]])

#create training set with equal number of different source and same source
train_writers2<-writers_combo %>% filter(writer.x==writer.y) %>% rbind(diff_sources)

#pairs to compare based on rows in sampled dataset
pairs_writers2<-train_writers2 %>% dplyr::select(c("row1","row2")) %>% as.matrix()

#distance measures 
#train_writers_all_woz<-calc_dist(w_writers2,pairs_writers2)
#write.csv(train_writers_all_woz, "train_writers_all_woz.csv", row.names = TRUE)
train_writers_all_woz<-read.csv("train_writers_all_woz.csv")
```

```{r}
#random forest
forest_writers_all_woz <- randomForest(
  as.formula(paste("y ~ ", paste(c(paste("c",c(1:40),sep=""),'euch_dist'),collapse= "+"))),
             data=train_writers_all_woz, ntree=200)
forest_writers_all_woz
importance(forest_writers_all_woz)
plot(forest_writers_all_woz)

#save trained random forest
#saveRDS(forest_writers_all_woz , "forest_writers_all_woz.RDS")
```

```{r}
#create a testing dataset
#samp_test_writers2 <- anti_join(w,samp_writers2)
#pairs_test_writers2 <- combinations(dim(samp_test_writers2)[1],2)
#test_writers2<-calc_dist(samp_test_writers2,pairs_test_writers2)
#write.csv(test_writers2, "test_writers2_w.csv", row.names = TRUE)
test_writers2_w<-read.csv("test_writers2_w.csv")
```

```{r}
prediction_writers2_w<-predict(forest_writers_all_woz, newdata = subset(test_writers2_w, select=-c(y)))
table(test_writers2_w[, "y"], prediction_writers2_w)
varimportanceplot_woz<-varImpPlot(forest_writers_all_woz, main="Variable Importance in Random Forest");varimportanceplot_woz

#png(file="varimportanceplot_woz.png",
#width=600, height=500)
#varImpPlot(forest_writers_all_woz, main="Variable Importance in WOZ Random Forest")
#dev.off()
```

```{r}
kde_data_woz<-plot_kdes(test_writers2_w,forest_writers_all_woz)+
  ggtitle("KDEs for Wizard of Oz Prompt");kde_data_woz
#ggsave("kde_data_woz.png")
```

```{r}
slrs_writers2_woz<-loo_slr(test_writers2_w,forest_writers_all_woz)
#saveRDS(slrs_writers2_woz,"slrs_writers2_woz.rds")
slr_data_woz<-plot_slr(slrs_writers2_woz)+
  ggtitle("SLRs for Wizard of Oz Prompt");slr_data_woz
#ggsave("slr_data_woz.png")
logslr_data_woz<-plot_logslr(slrs_writers2_woz)+
  ggtitle("SLRs for Wizard of Oz Prompt");logslr_data_woz
#ggsave("logslr_data_woz.png")
logslr2_data_woz<-plot_logslr2(slrs_writers2_woz)+
  ggtitle("SLRs for Wizard of Oz Prompt");logslr2_data_woz
#ggsave("logslr2_data_woz.png")
```
